**CLEAN CAFE DATASET**

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\power bi\raw_cafe_file_uncleaned.csv.csv")

In [5]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [6]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [8]:
df.shape

(10000, 8)

In [9]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [10]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [11]:
df['Quantity'] = pd.to_numeric(df['Quantity'],errors='coerce')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'],errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'],errors='coerce')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'],errors='coerce')

In [13]:
df.replace("UNKNOWN",np.nan,inplace=True)

In [14]:
df.replace("ERROR",np.nan,inplace=True)

In [16]:
df.duplicated().sum()

0

In [17]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [18]:
df['Item'] = df['Item'].fillna('Unknown item')
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Quantity'].median())
df['Payment Method'] = df['Payment Method'].fillna(df['Quantity'].mode()[0])
df['Location'] = df['Location'].fillna(df['Location'].mode()[0])

In [19]:
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity']*df['Price Per Unit'])

In [20]:
df = df.dropna(subset=['Transaction Date'])

In [21]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [23]:
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 3.0, 'Digital Wallet'], dtype=object)

In [24]:
df['Payment Method'] = df['Payment Method'].replace(["3.0", 3.0],pd.NA)
df['Payment Method'] = df['Payment Method'].fillna(df['Payment Method'].mode()[0])

C:\Users\HP\AppData\Local\Temp\ipykernel_18344\2694221352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Payment Method'] = df['Payment Method'].replace(["3.0", 3.0],pd.NA)
C:\Users\HP\AppData\Local\Temp\ipykernel_18344\2694221352.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Payment Method'] = df['Payment Method'].fillna(df['Payment Method'].mode()[0])

In [25]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    5212
Credit Card       2170
Cash              2158
Name: count, dtype: int64

In [27]:
df.to_csv("cleaned_cafe_data.csv",index=False)